remove index from everywhere it could possibly be stored
JoinSEEDS/seeds-smart-contracts pull request #297
Opened 2021-04-09 08:23 UTC by n13

2021-04-09 18:03 UTC, IanMendozaJaimes requested changes
In case of campaign invites, they should return their funds to the campaign before delete the invite

2021-04-14 14:45 UTC, n13 commented
> I think in case of campaign invites, they should return their funds to the campaign before delete the invite

Makes sense yes

2021-04-28 09:15 UTC, n13 commented
> I think in case of campaign invites, they should return their funds to the campaign before delete the invite

I am now sharing the code with cleanup, since it's so complicated - should work!

2021-04-28 09:35 UTC, n13 commented on src/seeds.onboarding.cpp
> +      count += 8;
+8 because that's a heavyweight operation there ;)

2021-04-30 00:52 UTC, IanMendozaJaimes approved these changes
Looks great!

2021-04-30 03:26 UTC, merged