Claim back unused invites #328
JoinSEEDS/seeds-smart-contracts pull request #347
Opened 2021-06-08 22:41 UTC by IanMendozaJaimes

- Added `chkcleanup` action to onboarding and added to the scheduler
- Added tests for onboarding and refactored scheduler tests

Fixes #328 

Contracts that need to be deployed:
- [ ] Onboarding

Other considerations:
- [ ] Permissions need to be updated
- [ ] Scheduler needs to be updated

2021-06-09 11:42 UTC, n13 requested changes
Looks perfect, only one minor change requested

2021-06-09 11:42 UTC, n13 commented on src/seeds.onboarding.cpp
> +
Not sure this works, IMO doing "rbegin()" is better than end() -- 1

2021-06-09 11:42 UTC, n13 commented on src/seeds.onboarding.cpp
> +
same here - use rbegin()

2021-06-09 11:42 UTC, n13 commented on src/seeds.onboarding.cpp
> +      std::make_tuple(start_id, max_id, config_get("batchsize"_n))
not sure cleanup can handle 200...

2021-06-09 11:42 UTC, n13 commented on src/seeds.onboarding.cpp
> +      std::make_tuple(start_id, max_id, config_get("batchsize"_n))
actually should be fine, it's x8 for each returned invite... 25 returned invites hopefully works

2021-06-09 16:37 UTC, IanMendozaJaimes commented
- I have changed the iterators in the chkcleanup function

2021-06-11 03:36 UTC, n13 approved these changes
Looks good! Will deploy shortly!

2021-06-13 11:18 UTC, merged

2021-06-13 11:39 UTC, n13 commented
I merged, but can't get onboarding test to succeed, can you look at it? Can't deploy until it's passing

'''
      next_key: ''
    }    ✔  Given cleanup ran: should have the correct timestamp entries

    {
      rows: [
        {
          invite_id: 0,
          transfer_quantity: '10.0000 SEEDS',
          sow_quantity: '5.0000 SEEDS',
          sponsor: 'seedsuseraaa',
          account: '',
          invite_hash: '063e5deabe176d0bc2ba72724f8f0696319ddeed7800b5109751f26fd0f02e51',
          invite_secret: '0000000000000000000000000000000000000000000000000000000000000000'
        },
        {
          invite_id: 1,
          transfer_quantity: '10.0000 SEEDS',
          sow_quantity: '5.0000 SEEDS',
          sponsor: 'seedsuserbbb',
          account: '',
          invite_hash: 'af6d775fcd1110329bc3a7e058171d8c5502436fe96624d24fe79c22a91efeb5',
          invite_secret: '0000000000000000000000000000000000000000000000000000000000000000'
        },
        {
          invite_id: 2,
          transfer_quantity: '10.0000 SEEDS',
          sow_quantity: '5.0000 SEEDS',
          sponsor: 'seedsuserbbb',
          account: '',
          invite_hash: 'b715fe2cb69014f9b7dddfabe8449924cdd787b595003180d72cff98bb3f5b57',
          invite_secret: '0000000000000000000000000000000000000000000000000000000000000000'
        }
      ],
      more: false,
      next_key: ''
    }    ✖  Given cleanup ran: should have the correct number of invites
    ----------------------------------------------------------------
        operator: deepEqual
        diff: "1" => "3"
        source: at checkInvites (/Users/elohim/play/seeds/seeds-smart-contracts/test/onboarding.test.js:1071:9)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async /Users/elohim/play/seeds/seeds-smart-contracts/test/onboarding.test.js:1116:5
        
        

    {
      rows: [ { id: 0, invite_id: 2, timestamp: 1623584299 } ],
      more: false,
      next_key: ''
    }    ✖  Given cleanup ran: should have the correct timestamp entries
    ----------------------------------------------------------------
        operator: deepEqual
        expected: [{"id": 0, "invite_id": 2}, {"id": 1, "invite_id": 2}]
        diff: [
        - 1: {"id":1,"invite_id":2}
        ]
        source: at checkInvites (/Users/elohim/play/seeds/seeds-smart-contracts/test/onboarding.test.js:1086:9)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async /Users/elohim/play/seeds/seeds-smart-contracts/test/onboarding.test.js:1116:5
        
        



  passed: 41,  failed: 2  of 43 tests  (15.1s)

'''

2021-06-13 11:45 UTC, n13 commented
Un-merged, but status didn't update

2021-06-16 05:59 UTC, n13 commented
Deployed as new PR - see here https://github.com/JoinSEEDS/seeds-smart-contracts/pull/360